var books = [
    {
        id: 1,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1654565596i/45154547.jpg",
        title: "A Desolation Called Peace",
        author: "Arkady Martine",
        genre: "Science Ficton",
        price: "R499.90",
        rands: 499.90,
    },
    {
        id: 2,
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1626710416l/58446227.jpg",
        title: "Sea of Tranquility",
        author: "Emily St. John Mandel",
        genre: "Science Fiction",
        price: "R349.90",
        rands: 499.90,
    },
    {
        id: 3,
        image: "https://booklounge.co.za/wp-content/uploads/2023/05/eyes-of-the-voic.jpg",
        title: "Eyes of the Void",
        author: "Adrian Tchaikovsky",
        genre: "Science Fiction",
        price: "R249.90",
        rands: 249.90,
    },
    {
        id: 4,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1627483822i/57850265.jpg",
        title: "How High We Go in the Dark",
        author: "Sequoia Nagamatsu",
        genre: "Science Fiction",
        price: "R349.90",
        rands: 349.90,
    },
    {
        id: 5,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1631539191i/40864030.jpg",
        title: "A Prayer for the Crown-Shy: A Monk and Robot Book",
        author: "Becky Chambers",
        genre: "Science Fiction",
        price: "R359.90",
        rands: 359.90,
    },
    {
        id: 6,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1652627981i/60784359.jpg",
        title: "Exiles",
        author: "Jane Harper",
        genre: "Thriller",
        price: "R349.90",
        rands: 349.90,
    },
    {
        id: 7,
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1675644340l/60833953.jpg",
        title: "Going Zero: A Novel",
        author: "Anthony McCarten",
        genre: "Thriller",
        price: "R609.90",
        rands: 609.90,
    },
    {
        id: 8,
        image: "https://www.panmacmillan.co.za/static/3480281e927985f072e210bdece5445c/a6fd0/9781529093643.webp",
        title: "Red Queen",
        author: "Juan Gómez-Jurado",
        genre: "Thriller",
        price:"R289.90",
        rands: 289.90,
    },
    {
        id: 9,
        image: "https://booklounge.co.za/wp-content/uploads/2023/03/marriage-act.jpg",
        title: "The Marriage Act",
        author: "John Marrs",
        genre: "Thriller",
        price: "R339.90",
        rands: 339.90,
    },
    {
        id: 10,
        image: "https://booklounge.co.za/wp-content/uploads/2023/03/murders-at-fleat-1.jpg",
        title: "The Murders at Fleat House",
        author: "Lucinda Riley",
        genre: "Thriller",
        price: "R349.90",
        rands: 349.90,
    },
    {
        id: 11,
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1641926961l/59040894.jpg",
        title: "A Caribbean Heiress in Paris",
        author: "Adriana Herrera",
        genre: "Romance",
        price: "R344.90",
        rands: 344.90,
    },
    {
        id: 12,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1638467995i/59345253.jpg",
        title: "Something Wilder",
        author: "Christina Lauren",
        genre: "Romance",
        price: "R230.90",
        rands: 230.90,
    },
    {
        id: 13,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1646064290i/57007967.jpg",
        title: "A Lady for a Duke",
        author: "Alexis Hall",
        genre: "Romance",
        price: "R199.90",
        rands: 199.90,
    },
    {
        id: 14,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1626896884i/57693870.jpg",
        title: "In a New York Minute",
        author: "Kate Spencer",
        genre: "Romance",
        price: "R229.90",
        rands: 229.90,
    },
    {
        id: 15,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1663130429i/60568471.jpg",
        title: "Before I Let Go",
        author: "Kennedy Ryan",
        genre: "Romance",
        price: "R324.90",
        rands: 324.90,
    },
    {
        id: 16,
        image: "https://kbimages1-a.akamaihd.net/66f152ca-cb03-4e26-ae64-63f3c9154df8/353/569/90/False/moby-dick-89.jpg",
        title: "Touching the Void",
        author: "Joe Simpson",
        genre: "Adventure",
        price: "R124.90",
        rands: 124.90,
    },
    {
        id: 17,
        image: "https://kbimages1-a.akamaihd.net/3d73fdbd-2502-43a4-b98c-f5d0f42b8be1/353/569/90/False/the-call-of-the-wild-344.jpg",
        title: "The Call of the Wild",
        author: "Jack London",
        genre: "Adventure",
        price: "R"
    },
]